// swift-tools-version:5.3
// Auto-generated by release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "ProofKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ProofKit", targets: ["ProofKit"])
    ],
    targets: [
        .binaryTarget(
            name: "ProofKit",
            url: "https://github.com/scale-soft/ProofKit-dist/releases/download/v1_0/ProofKit-v1_0.xcframework.zip",
            checksum: "3b4f2621c767f86817ea9eda136e14080ec5c908a2cbfc0d1a26371ac2c3d8a3"
        )
    ]
)
