// swift-tools-version:5.3
// Auto-generated by release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "ProofKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ProofKit", targets: ["ProofKit"])
    ],
    targets: [
        .binaryTarget(
            name: "ProofKit",
            url: "https://github.com/scale-soft/ProofKit-dist/releases/download/v1_0/ProofKit-v1_0.xcframework.zip",
            checksum: "3e8c00a75cb5efd8a9ab21a909ff457eeadb4c190c4e5a2a212b7eb8a2c4aded"
        )
    ]
)
