// swift-tools-version:5.3
// Auto-generated by release pipeline — do not edit manually.
import PackageDescription

let package = Package(
    name: "ProofKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "ProofKit", targets: ["ProofKit"])
    ],
    targets: [
        .binaryTarget(
            name: "ProofKit",
            url: "https://github.com/scale-soft/ProofKit-dist/releases/download/v1_0-ios/ProofKit-v1_0-ios.xcframework.zip",
            checksum: "7c809edfeb4346d96ef6407bb98dca8b832a325a0f2df3a8bfa5d137c52c6967"
        )
    ]
)
